//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeDesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assembly
    {
        public int SubComponents_PK { get; set; }
        public int ProductComponents_FK { get; set; }
        public string SubComponentDescription { get; set; }
        public int SubComponentQty { get; set; }
        public string DrawingNumber { get; set; }
        public string DrawingRevision { get; set; }
        public string SectionDescription { get; set; }
        public Nullable<decimal> SectionLength { get; set; }
        public Nullable<decimal> SectionWeight { get; set; }
        public Nullable<int> BarcodeRequired { get; set; }
        public string PartsArray { get; set; }
        public Nullable<int> AmICommon { get; set; }
        public Nullable<int> RandUID { get; set; }
        public Nullable<int> Galvanisable { get; set; }
        public string TempSuffix { get; set; }
        public Nullable<int> Sherardize { get; set; }
        public Nullable<int> Paint { get; set; }
        public Nullable<int> ValidAss { get; set; }
        public Nullable<decimal> ActualQuantity { get; set; }
        public Nullable<int> InBucket { get; set; }
    }
}
