//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeDesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int Contract_PK { get; set; }
        public string ContractName { get; set; }
        public string ContractDetails { get; set; }
        public string JobNumberPrefix { get; set; }
    }
}
