//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeDesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch
    {
        public int Dispactch_PK { get; set; }
        public int HutchDispRefID { get; set; }
        public int ContractID { get; set; }
        public int IsPending { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string DeliveryNotes { get; set; }
        public int DispatchedBy { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string Addr3 { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string PostCode { get; set; }
    }
}
