//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeDesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalvDelivery
    {
        public int GalvDelID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string GalvDestination { get; set; }
        public Nullable<int> PORaised { get; set; }
        public Nullable<int> WagonType { get; set; }
        public Nullable<int> PO_FK { get; set; }
        public Nullable<int> RejectedOnDelivery { get; set; }
    }
}
